<?php

$books = [
    ['id' => 1, 'title' => 'Quarta Asa #1', 'author' => 'Rebecca Yarros', 'description' => 'Um dragão sem seu cavaleiro é uma tragédia. Um cavaleiro sem seu dragão é um homem morto. Em Quarta Asa, best-seller #1 do The New York Times, uma jovem precisa sobreviver ao treinamento em uma escola de elite para poderosos cavaleiros de dragões, onde a única regra é se formar... ou morrer tentando. ... '],
    ['id' => 2, 'title' => 'Quarta Asa #2', 'author' => 'Rebecca Yarros', 'description' => 'Um dragão sem seu cavaleiro é uma tragédia. Um cavaleiro sem seu dragão é um homem morto. Em Quarta Asa, best-seller #1 do The New York Times, uma jovem precisa sobreviver ao treinamento em uma escola de elite para poderosos cavaleiros de dragões, onde a única regra é se formar... ou morrer tentando. ... '],
    ['id' => 3, 'title' => 'Quarta Asa #3', 'author' => 'Rebecca Yarros', 'description' => 'Um dragão sem seu cavaleiro é uma tragédia. Um cavaleiro sem seu dragão é um homem morto. Em Quarta Asa, best-seller #1 do The New York Times, uma jovem precisa sobreviver ao treinamento em uma escola de elite para poderosos cavaleiros de dragões, onde a única regra é se formar... ou morrer tentando. ... '],
    ['id' => 4, 'title' => 'Quarta Asa #4', 'author' => 'Rebecca Yarros', 'description' => 'Um dragão sem seu cavaleiro é uma tragédia. Um cavaleiro sem seu dragão é um homem morto. Em Quarta Asa, best-seller #1 do The New York Times, uma jovem precisa sobreviver ao treinamento em uma escola de elite para poderosos cavaleiros de dragões, onde a única regra é se formar... ou morrer tentando. ... '],
    ['id' => 5, 'title' => 'Quarta Asa #5', 'author' => 'Rebecca Yarros', 'description' => 'Um dragão sem seu cavaleiro é uma tragédia. Um cavaleiro sem seu dragão é um homem morto. Em Quarta Asa, best-seller #1 do The New York Times, uma jovem precisa sobreviver ao treinamento em uma escola de elite para poderosos cavaleiros de dragões, onde a única regra é se formar... ou morrer tentando. ... '],
];
